### ISSUE TITLE
Compte rendu FOAD

### ISSUE THREAD

**Issue by ghost** [djasan/foad-sf-03#1]
- Ton dépôt est brouillon
- Je ne vois pas le travail final du la branch developp
- Plusieurs branch develop

**Comment by djasan** [comment]
j ai tourne en boucle jusqu a 3h du mat et j ai abandonné, je ne parvenais pas a installer la base de données, j ai pas suivi si il fallait xampp ou non etc j ai essayé avec chat gpt et j ai recommencé 4 fois le projet c est devenu n importe quoi, je ne comprends pas de toutes c j ai pas suivi.. merci envoyé : 11 janvier 2024 à 09:46de : formeka ***@***.***>à : djasan/foad-sf-03 ***@***.***>cc : Subscribed ***@***.***>objet : [djasan/foad-sf-03] Compte rendu FOAD (Issue #1) Ton dépôt est brouillonJe ne vois pas le travail final du la branch developpPlusieurs branch develop—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

**Comment by ghost** [comment]
Ne ti'inquiete pas , on va revoir tout ça.
